[package]
name = "ella"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
wasm-encoder = "0.36.2"
wasmprinter = "0.2.72"
clap = { version = "4.4.8", features = ["derive"] }
